global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]
  - job_name: pushgateway
    static_configs:
      - targets: ["pushgateway:9091"]
